name: Samsung Galaxy A50

on:
  push:
    branches: [ master ]
  watch:
    types: [ workflow_dispatch, started ]

jobs:
  twrp:
    name: Build TeamWin Recovery Project (TWRP)
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Run pre-build housekeeping
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
        sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo apt update
        sudo apt -y autoremove --purge
        sudo apt clean
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Install and update build dependencies
      run: |
        sudo apt update
        sudo apt full-upgrade
        sudo apt install git-core gnupg build-essential libelf-dev kernel-package bzip2 openjdk-8-jdk lib32stdc++6 libc6-dev-i386 git flex bison gperf zip curl zlib1g-dev gcc-multilib g++-multilib lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip jq -y
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo

    - name: Set variables for compilation
      id: var
      run: |
        echo "::set-output name=recovery_url::$(jq -r '.recovery_url' twrp.json)"
        echo "::set-output name=recovery_branch::$(jq -r '.recovery_branch' twrp.json)"
        echo "::set-output name=git_username::$(jq -r '.git_username' twrp.json)"
        echo "::set-output name=git_email::$(jq -r '.git_email' twrp.json)"
        echo "::set-output name=use_own_dt::$(jq -r '.use_own_dt' twrp.json)"
        echo "::set-output name=dt_url::$(jq -r '.dt_url' twrp.json)"
        echo "::set-output name=dt_remote::$(jq -r '.dt_remote' twrp.json)"
        echo "::set-output name=dt_branch::$(jq -r '.dt_branch' twrp.json)"
        echo "::set-output name=dt_path::$(jq -r '.dt_path' twrp.json)"
        echo "::set-output name=device_code::$(jq -r '.device_code' twrp.json)"
        echo "::set-output name=fix_product::$(jq -r '.fix_product' twrp.json)"
        echo "::set-output name=fix_misscom::$(jq -r '.fix_misscom' twrp.json)"
        echo "::set-output name=fix_busybox::$(jq -r '.fix_busybox' twrp.json)"
        echo "::set-output name=fix_branch::$(jq -r '.fix_branch' twrp.json)"
        echo "::set-output name=date::$(date +%F)"

    - name: Sync sources with source
      run: |
        PATH="~/bin:$PATH"
        repo init --depth=1 -u ${{ steps.var.outputs.recovery_url }} -b ${{ steps.var.outputs.recovery_branch }}
        git clone ${{ steps.var.outputs.dt_url }} -b ${{ steps.var.outputs.dt_branch }} ${{ steps.var.outputs.dt_path }}
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
        ls -al

    - name: Build recovery image
      run: |
        PATH="~/bin:$PATH"
        tree device
        export ALLOW_MISSING_DEPENDENCIES=true
        export TARGET_DEVICE_ALT="a50, a50dd"
        export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
        export TARGET_ARCH="arm64"
        export TW_DEFAULT_LANGUAGE="en"
        export USE_CCACHE="1"
        export LZMA_RAMDISK_TARGETS="recovery"
        source build/envsetup.sh
        lunch omni_${{ steps.var.outputs.device_code }}-eng
        sudo $(mka recoveryimage -j$(nproc --all))

    - name: Upload recovery release artifacts
      uses: Hs1r1us/Release-AIO@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.RECOVERY }}
      with:
        tag_name: ci_${{ github.run_number }}
        release_name: ci_${{ github.run_number }}-TWRP
        body: Android Third-Party Recovery built by ${{ steps.var.outputs.git_username }}
        asset_files: './out/target/product/a50dd/recovery.img'

  shrp:
    name: Build SkyHawk Recovery Project (SHRP)
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Run pre-build housekeeping
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
        sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo apt update
        sudo apt -y autoremove --purge
        sudo apt clean
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Install and update build dependencies
      run: |
        sudo apt update
        sudo apt full-upgrade
        sudo apt install git-core gnupg build-essential libelf-dev kernel-package openjdk-8-jdk bzip2 lib32stdc++6 libc6-dev-i386 git flex bison gperf zip curl zlib1g-dev gcc-multilib g++-multilib lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip jq -y
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo

    - name: Set variables for compilation
      id: var
      run: |
        echo "::set-output name=recovery_url::$(jq -r '.recovery_url' shrp.json)"
        echo "::set-output name=recovery_branch::$(jq -r '.recovery_branch' shrp.json)"
        echo "::set-output name=git_username::$(jq -r '.git_username' shrp.json)"
        echo "::set-output name=git_email::$(jq -r '.git_email' shrp.json)"
        echo "::set-output name=use_own_dt::$(jq -r '.use_own_dt' shrp.json)"
        echo "::set-output name=dt_url::$(jq -r '.dt_url' shrp.json)"
        echo "::set-output name=dt_remote::$(jq -r '.dt_remote' shrp.json)"
        echo "::set-output name=dt_branch::$(jq -r '.dt_branch' shrp.json)"
        echo "::set-output name=dt_path::$(jq -r '.dt_path' shrp.json)"
        echo "::set-output name=device_code::$(jq -r '.device_code' shrp.json)"
        echo "::set-output name=fix_product::$(jq -r '.fix_product' shrp.json)"
        echo "::set-output name=fix_misscom::$(jq -r '.fix_misscom' shrp.json)"
        echo "::set-output name=fix_busybox::$(jq -r '.fix_busybox' shrp.json)"
        echo "::set-output name=fix_branch::$(jq -r '.fix_branch' shrp.json)"
        echo "::set-output name=date::$(date +%F)"

    - name: Sync sources with source
      run: |
        PATH="~/bin:$PATH"
        repo init --depth=1 -u ${{ steps.var.outputs.recovery_url }} -b ${{ steps.var.outputs.recovery_branch }}
        git clone ${{ steps.var.outputs.dt_url }} -b ${{ steps.var.outputs.dt_branch }} ${{ steps.var.outputs.dt_path }}
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
        ls -al

    - name: Build recovery image
      run: |
        PATH="~/bin:$PATH"
        tree device
        export ALLOW_MISSING_DEPENDENCIES=true
        export TARGET_DEVICE_ALT="a50, a50dd"
        export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
        export TARGET_ARCH="arm64"
        export TW_DEFAULT_LANGUAGE="en"
        export USE_CCACHE="1"
        export LZMA_RAMDISK_TARGETS="recovery"
        source build/envsetup.sh
        lunch omni_${{ steps.var.outputs.device_code }}-eng
        sudo $(mka recoveryimage -j$(nproc --all))

    - name: Upload recovery release artifacts
      uses: Hs1r1us/Release-AIO@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.RECOVERY }}
      with:
        tag_name: ci_${{ github.run_number }}
        release_name: ci_${{ github.run_number }}-SHRP
        body: Android Third-Party Recovery built by ${{ steps.var.outputs.git_username }}
        asset_files: './out/target/product/a50dd/recovery.img'
